/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import About from "../components/About";
import Accordeon from "../components/Accordeon";
import Education from "../components/Education";
import Header from "../components/Header";
import HeaderNav from "../components/HeaderNav";
import PeriodCard from "../components/PeriodCard";
import Work from "../components/Work";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeaderNav />

      <main className="container">
        <section className="mt-4">
          <Header id="about">About me</Header>
          <About />
        </section>
        <section>
          <Header id="education">Education</Header>
          <Education />
        </section>
        <section>
          <Header id="work">Work experience</Header>
          <Work />
        </section>
        <section>
          <Header id="projects">Projects</Header>
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus
          exercitationem rem facilis animi consequatur nesciunt est at eligendi,
          maiores laboriosam saepe optio aliquam iste dignissimos ex molestias,
          officia, adipisci aperiam hic rerum quos aliquid beatae voluptate!
          Velit saepe, quibusdam accusamus est eligendi reprehenderit laboriosam
          corporis aliquam voluptatum corrupti alias in, cupiditate temporibus
          voluptate? Ducimus sequi nulla ea, tempora officiis voluptates
          exercitationem veritatis ad inventore architecto ipsa nam, repellendus
          obcaecati impedit, voluptate quod saepe laboriosam vel placeat
          pariatur! Dolorem minima nesciunt officiis labore nulla? Sunt amet
          quia fuga magni, ex labore eos voluptas voluptate molestiae cumque?
          Itaque numquam deserunt possimus maxime!
        </section>
        <section>
          <Header id="contact">Contact me</Header>
          Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deserunt,
          quasi! Delectus minus voluptates quia vero error dolorem quidem
          architecto aliquid. Neque impedit iusto facilis corporis possimus?
          Dolores, soluta qui. Nesciunt, earum quas! Culpa, ipsam omnis dolorum
          aperiam, dolores consequatur maxime placeat veritatis delectus iure ex
          inventore possimus tempora suscipit, cum deleniti consequuntur animi!
          Explicabo, blanditiis nesciunt quas fugiat illum officiis sequi
          perferendis quia, voluptatum saepe vitae recusandae? Magnam voluptate
          dolorem quibusdam cum rerum, odio voluptatem tempore eaque eum porro.
          Ea nam distinctio temporibus, saepe iusto dolorum aperiam dicta odit.
          Laboriosam ex nam corrupti eum soluta quisquam repudiandae doloribus
          commodi nihil!
        </section>
      </main>
    </div>
  );
}
