/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import About from "../components/About";
import Accordeon from "../components/Accordeon";
import Header from "../components/Header";
import HeaderNav from "../components/HeaderNav";
import PeriodCard from "../components/PeriodCard";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeaderNav />

      <main className="container">
        <section className="mt-4">
          <Header id="about">About me</Header>
          <About />
        </section>
        <section>
          <Header id="education">Education</Header>
          <PeriodCard
            dateFrom={new Date("2001-09-01")}
            dateTo={new Date("2013-06-01")}
            dateFormat="mm-yyyy"
            category="School"
            showDateDifference
            dateDifferenceFormat="yyyy"
          >
            <div>
              <span>Liceul Constantin Stere</span>
              <br />
              <small>Soroca. Moldova.</small>
            </div>
          </PeriodCard>
          <PeriodCard
            dateFrom={new Date("2013-09-01")}
            dateTo={new Date("2016-06-01")}
            dateFormat="mm-yyyy"
            category="Bachelor"
            className="mt-2"
            showDateDifference
            dateDifferenceFormat="yyyy"
          >
            <div>
              <span>Moldova State University</span>
              <br />
              <span>Marketing and Logstics</span>
              <br />
              <small>Chisinau. Moldova.</small>
            </div>
          </PeriodCard>

          <PeriodCard
            dateFrom={new Date("2016-09-01")}
            dateTo={new Date("2018-06-01")}
            dateFormat="mm-yyyy"
            category="Master"
            className="mt-2"
            showDateDifference
            dateDifferenceFormat="yyyy"
          >
            <div>
              <span>Moldova State University</span>
              <br />
              <span>Marketing</span>
              <br />
              <small>Chisinau. Moldova.</small>
            </div>
          </PeriodCard>
        </section>
        <section>
          <Header id="work">Work experience</Header>
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dicta earum
          repudiandae perspiciatis inventore quisquam optio in vitae, labore
          molestias eligendi quia voluptatem sequi provident commodi deleniti
          doloribus eius tenetur. Accusamus autem, eveniet dolore excepturi quod
          temporibus nobis repellendus rem tenetur officiis praesentium totam
          aliquam sunt itaque quidem nulla voluptate inventore animi dolor
          aliquid natus hic nesciunt soluta illo. Vitae, tenetur quasi. Aut
          possimus dolores porro soluta, accusantium et error quos odio
          repudiandae saepe amet est voluptatem dolorem veniam iste, laudantium
          labore dicta reiciendis eos esse similique. Nobis commodi minus omnis
          veritatis dolor, reiciendis nemo porro cumque aliquid quidem eum et.
        </section>
        <section>
          <Header id="projects">Projects</Header>
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus
          exercitationem rem facilis animi consequatur nesciunt est at eligendi,
          maiores laboriosam saepe optio aliquam iste dignissimos ex molestias,
          officia, adipisci aperiam hic rerum quos aliquid beatae voluptate!
          Velit saepe, quibusdam accusamus est eligendi reprehenderit laboriosam
          corporis aliquam voluptatum corrupti alias in, cupiditate temporibus
          voluptate? Ducimus sequi nulla ea, tempora officiis voluptates
          exercitationem veritatis ad inventore architecto ipsa nam, repellendus
          obcaecati impedit, voluptate quod saepe laboriosam vel placeat
          pariatur! Dolorem minima nesciunt officiis labore nulla? Sunt amet
          quia fuga magni, ex labore eos voluptas voluptate molestiae cumque?
          Itaque numquam deserunt possimus maxime!
        </section>
        <section>
          <Header id="contact">Contact me</Header>
          Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deserunt,
          quasi! Delectus minus voluptates quia vero error dolorem quidem
          architecto aliquid. Neque impedit iusto facilis corporis possimus?
          Dolores, soluta qui. Nesciunt, earum quas! Culpa, ipsam omnis dolorum
          aperiam, dolores consequatur maxime placeat veritatis delectus iure ex
          inventore possimus tempora suscipit, cum deleniti consequuntur animi!
          Explicabo, blanditiis nesciunt quas fugiat illum officiis sequi
          perferendis quia, voluptatum saepe vitae recusandae? Magnam voluptate
          dolorem quibusdam cum rerum, odio voluptatem tempore eaque eum porro.
          Ea nam distinctio temporibus, saepe iusto dolorum aperiam dicta odit.
          Laboriosam ex nam corrupti eum soluta quisquam repudiandae doloribus
          commodi nihil!
        </section>
      </main>
    </div>
  );
}
