/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import About from "../components/About";
import Accordeon from "../components/Accordeon";
import Education from "../components/Education";
import Header from "../components/Header";
import HeaderNav from "../components/HeaderNav";
import PeriodCard from "../components/PeriodCard";
import Projects from "../components/Projects";
import Work from "../components/Work";

export default function Home() {
  return (
    <div>
      <Head>
        <title>AndreiD049&apos;s page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeaderNav />

      <main className="container">
        <section className="mt-4">
          <Header id="about">About me</Header>
          <About />
        </section>
        <section>
          <Header id="education">Education</Header>
          <Education />
        </section>
        <section>
          <Header id="work">Work experience</Header>
          <Work />
        </section>
        <section>
          <Header id="projects">Projects</Header>
          <p>Below is a list of pet-projects I built and saved. For each one, i tried to summarize what the project is about and what I have learned from it. Links to source code and any other related resources are included.</p>
          <Projects />
        </section>
        <section>
          <Header id="contact">Contact me</Header>
          <p>You can contact me by <a href="mailto:andrei.dimitrascu.94@gmail.com">email</a> or via <a href="http://t.me/andreid049" target="_blank" rel="noopener noreferrer">telegram</a>.</p>
          <p>P.S. I don&apos;t check my messages too often so i apologize for delayed replies. ¯\_( ͡° ͜ʖ ͡°)_/¯</p>
        </section>
      </main>
      <footer className="container text-center">
        <div className="mt-5 mb-3">
          &#0169; <a href="https://github.com/AndreiD049" target="_blank" rel="noopener noreferrer">Andrei Dimitrascu</a> &#8212; 2021
        </div>
      </footer>
    </div>
  );
}
